name: iter-env
channels:
  - conda-forge
  - defaults
dependencies:
  - fenics-dolfinx=0.9.0
  - matplotlib
  - scipy
  - pandas
  - pint # need to install pint with conda to avoid conflicts (HTM)
  - ipykernel
  - scifem
  - festim
  - pip
  - pip:
      - git+https://github.com/kaelyndunnell/hisp@fix-b-bins